sudo: required
services:
  - docker

before_install:
  - docker build -t nickrybak/client-test -f ./client/Dockerfile-dev ./client

script:
  - docker run nickrybak/client-test npm run test -- --coverage

after_success:
  - docker build -t nickrybak/multi-client ./client
  - docker build -t nickrybak/multi-server ./server
  - docker build -t nickrybak/multi-worker ./worker
  - docker build -t nickrybak/multi-nginx ./nginx
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Push that images to Docker Hub
  - docker push nickrybak/multi-client
  - docker push nickrybak/multi-server
  - docker push nickrybak/multi-worker
  - docker push nickrybak/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-447230092748
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY