sudo: required
services:
  - docker

before_install:
  - docker build -t nickrybak/client-test -f ./client/Dockerfile-dev ./client

script:
  - docker run nickrybak/client-test npm run test -- --coverage

after_success:
  - docker build -t nickrybak/multi-client ./client
  - docker build -t nickrybak/multi-server ./server
  - docker build -t nickrybak/multi-worker ./worker
  - docker build -t nickrybak/multi-nginx ./nginx
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Push that images to Docker Hub
  - docker push nickrybak/multi-client
  - docker push nickrybak/multi-server
  - docker push nickrybak/multi-worker
  - docker push nickrybak/multi-nginx